version: '3.8'

services:
  deepfake-detect:
    image: deepfake-detect:v1
    ports:
     - 8000:8000
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]


