version: '3.8'

services:
  deepfake-detect:
    build: deepfake-detect/.
    ports:
     - 8000:8000
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]


