version: '3.8'

services:
  deepfake-detect:
    image: europe-west3-docker.pkg.dev/junction-budapest-2023/main/deepfake-detect:v1
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  # open-closed-eye-detect:
  #   image: europe-west3-docker.pkg.dev/junction-budapest-2023/main/open-closed-eye-detect:v1
  #   deploy:
  #     resources:
  #       reservations:
  #         devices:
  #           - driver: nvidia
  #             count: 1
  #             capabilities: [gpu]
              
  audio-fake-detection:
    image: europe-west3-docker.pkg.dev/junction-budapest-2023/main/audio-fake-detection:v1
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
  
  # lips-movement-detection:
  #   image: europe-west3-docker.pkg.dev/junction-budapest-2023/main/lips-movement-detection:v1
  #   deploy:
  #     resources:
  #       reservations:
  #         devices:
  #           - driver: nvidia
  #             count: 1
  #             capabilities: [gpu]

  whisper-large-v3:
    image: europe-west3-docker.pkg.dev/junction-budapest-2023/main/whisper-large-v3:v1
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  one-person-detect:
    image: europe-west3-docker.pkg.dev/junction-budapest-2023/main/one-person-detect:v1
    environment:
      CONF_THRESHOLD: "0.25"
      IOU_THRESHOLD: "0.45"
      AGNOSTIC_NMS: "False"
      MAX_DET: "1000"
      MAX_VIDEO_LEN_SECOND: "150"
      MAX_FPS: "200"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  redis:
    image: redis:latest
    command: redis-server --save 60 1 --loglevel warning
    volumes:
      - redis-data:/data
    ports:
      - "6379:6379"

  nginx:
    image: nginx:latest
    ports:
      - "8000:8000"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - deepfake-detect
      # - open-closed-eye-detect
      - audio-fake-detection
      # - lips-movement-detection
      - whisper-large-v3
      - one-person-detect

volumes:
  redis-data: